name = "app"
version = "1.0.0"

[erlang]
application_start_module = "app"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
wisp = ">= 1.8.0 and < 2.0.0"
gleam_http = ">= 4.1.0 and < 5.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
gleam_erlang = ">= 1.2.0 and < 2.0.0"
mist = ">= 5.0.2 and < 6.0.0"
pog = ">= 4.0.0 and < 5.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
argus = ">= 1.0.3 and < 2.0.0"
gwt = ">= 2.1.1 and < 3.0.0"
gleam_time = ">= 1.3.0 and < 2.0.0"
gleam_crypto = ">= 1.5.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
squirrel = ">= 4.0.0 and < 5.0.0"
