ifneq (,$(wildcard ./.env))
    include .env
    export
endif

squirel:
	DATABASE_URL=$(GOOSE_DBSTRING) PORT=$(PORT) SECRET_KEY_BASE=$(SECRET_KEY_BASE) JWT_SECRET=$(JWT_SECRET) MODE="PACKAGE" gleam run -m squirrel

run:
	DATABASE_URL=$(GOOSE_DBSTRING) PORT=$(PORT) SECRET_KEY_BASE=$(SECRET_KEY_BASE) JWT_SECRET=$(JWT_SECRET) MODE="START" gleam run

tests:
	DATABASE_URL=$(GOOSE_DBSTRING) PORT=$(PORT) SECRET_KEY_BASE=$(SECRET_KEY_BASE) JWT_SECRET=$(JWT_SECRET) MODE="TEST" gleam test
